### ISSUE TITLE
Add more general tech meetups

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-meetups#17]
Let's add some general tech meetups to the README. 

If you are new to contributing to the repository, please read through the [contributing guidelines](https://github.com/thisdot/tech-meetups/blob/main/CONTRIBUTING.md). 
If you need help with making your first contribution, please reach out on our [discord channel](https://discord.com/invite/u7gqGcpR56).

**Please note**
This issue will stay open so multiple people can contribute 👍

**Comment by Nerajno** [comment]
Can i have this ?

**Comment by jdwilkin4** [comment]
HI @Nerajno ! 

This issue will stay open for multiple contributors and won't be assigned to anyone.
Feel free to open up a PR with your tech meetup suggestions. 👍

**Comment by meg-gutshall** [comment]
I have a bunch to drop in here! Will do it either tonight or over the weekend. 🎉
