### ISSUE TITLE
Add more React meetups

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-meetups#19]
Let's add some React meetups to the README. 

If you are new to contributing to the repository, please read through the [contributing guidelines](https://github.com/thisdot/tech-meetups/blob/main/CONTRIBUTING.md). 
If you need help with making your first contribution, please reach out on our [discord channel](https://discord.com/invite/u7gqGcpR56).

**Please note**
This issue will stay open so multiple people can contribute 👍

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by jdwilkin4** [comment]
HI @Asmit2952 ! 

This issue is open for multiple contributors to work on.
Read through the contributing guidelines and create a PR with your react additions.

**Comment by Asmit2952** [comment]
Great! Will work on it now
