### ISSUE TITLE
Alphabetize lists and remove duplicates

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-meetups#21]
Some of the lists are out of order and need to be alphabetized again.
Please go through each of the categories, and sort them in alphabetical order.
If there are duplicates, please remove them after the list has been put in order. 

If you are interested in working on this issue, please comment below and it will be assigned to you.
If you are new to this repository, please read through the [contributing docs](https://github.com/thisdot/tech-meetups/blob/main/CONTRIBUTING.md) first.

**Please note**: this issue will be assigned on a first come basis. Please do not start work on this issue until it has been assigned to you.

**Comment by jayantchaudhari18** [comment]
Hey @jdwilkin4, Can you please assign this issue to me?

**Comment by jdwilkin4** [comment]
@bautistaaa 

I have assigned you the issue since you responded first.
But in the future, please make sure to carefully read through the issue because there was a disclaimer in there about not working on the issue until it was assigned 👍

**Comment by jdwilkin4** [comment]
HI @jayantchaudhari18 ! 

Thank you for this issue! 
It has already been assigned to someone else but we have 5 other open issues if you are interested in working on one of those 👍
